spring.datasource.url=jdbc:postgresql://babar.db.elephantsql.com/gtigtzub
spring.datasource.username=gtigtzub
spring.datasource.password=njV93IC85YGqPPjFPRpFLdDq11SFhw8U
spring.datasource.driver-class-name=org.postgresql.Driver

external.api.token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJodHRwczovL3N0ZWFtY29tbXVuaXR5LmNvbS9vcGVuaWQvaWQvNzY1NjExOTgxMTA4NTk1MzMiLCJ1bmlxdWVfbmFtZSI6Im1hw6d1ZW4iLCJTdWJqZWN0IjoiMmJjNTVlYTgtMDUxYy00MGU4LWI2Y2YtZjUwNjI5NDRiYTMyIiwiU3RlYW1JZCI6IjE1MDU5MzgwNSIsIm5iZiI6MTY4MjM2OTkwMywiZXhwIjoxNzEzOTA1OTAzLCJpYXQiOjE2ODIzNjk5MDMsImlzcyI6Imh0dHBzOi8vYXBpLnN0cmF0ei5jb20ifQ.YcPGhMt1679U-TNI74iKB3Sgkmo2joGHge1rCMYG438