spring.datasource.url=jdbc:postgresql://babar.db.elephantsql.com/gtigtzub
spring.datasource.username=gtigtzub
spring.datasource.password=njV93IC85YGqPPjFPRpFLdDq11SFhw8U
#spring.datasource.url=jdbc:postgresql://localhost:5432/dotaslz
#spring.datasource.username=postgres
#spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

external.api.token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJodHRwczovL3N0ZWFtY29tbXVuaXR5LmNvbS9vcGVuaWQvaWQvNzY1NjExOTgxMTA4NTk1MzMiLCJ1bmlxdWVfbmFtZSI6Im1hw6d1ZW4iLCJTdWJqZWN0IjoiMmJjNTVlYTgtMDUxYy00MGU4LWI2Y2YtZjUwNjI5NDRiYTMyIiwiU3RlYW1JZCI6IjE1MDU5MzgwNSIsIm5iZiI6MTY4NDI1MzExNCwiZXhwIjoxNzE1Nzg5MTE0LCJpYXQiOjE2ODQyNTMxMTQsImlzcyI6Imh0dHBzOi8vYXBpLnN0cmF0ei5jb20ifQ.oaTPc42w-P7o8-Rj9XntlGaBAiNHmLfZRdWsfVDjOaU
